name: internet_kids_website
description: "The official website for Internet Kids audio plugins"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.11.0
  firebase_storage: ^11.2.0
  firebase_auth: ^4.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dartz: ^0.10.1
  url_launcher: ^6.2.2
  google_fonts: ^4.0.4
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env
